apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
    annotations:
        reloader.stakater.com/match: "true"
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:4OfSUq6lmk0=,iv:g6bnqOtuQ563Y1HoLYWJy4xhqQoSPTOLpnmmXQgsG78=,tag:ipCI4saxf9HCxB9g7Iku0A==,type:str]
    password: ENC[AES256_GCM,data:vIXhwXGQfxNFW5sqwbyLotUVoccTT3eaoO7OY9oEl6uJYCyY74Owvw==,iv:BeGiKATNWT/YQtLYCgRgNVDAclJIu84t1eSoxcd4ITA=,tag:ufizz2AQZsnPTZ5IZBKArQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VXN5elg2dk1NL3RvZE5u
            cHQ1NmlvQUd3WUt3MTBzTXFFOWQwTk1pcTMwCkVPTTBRUUl5NkpQYkRnMm5PQjcz
            Smh0MWxFWE5oWjMya1ZuRmpIaVdCbjQKLS0tIFBoS29hZi9CcGFBWjV6Mm5yNnhM
            aTl2YjJ1a2RJS3pjYytOeS9OK3hpdjAKsIxOtks15jirpd5FMxNr2IpMkp7/vFYD
            csJySm9u4XJPDyz3qk7zPYYlPalKF2vq4F0dnQZ1zBs1YzUJGElN1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T12:19:49Z"
    mac: ENC[AES256_GCM,data:HmfWxqJUQgWWfsbDa2uyNEcj8glK2s6mE72kapy8Am2wwCIPvO1330EpGA6fIOwdmv3ryTOOliH/qwsGWJJu71i2sKMSuV8UaKYDv8cnSz1CzG/8fLDJE+VRZTyQxiUfHdy2dJY5JZBc7B8Y1GUUaCxnRHxhpa4MqPRPA+YTpwU=,iv:9joBrvngvOgjMsMb4oVLn1b3+Efw1X2OgXB1zlwMVrs=,tag:A1CNBWUZAx5EJIrLy6DknQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    annotations:
        reloader.stakater.com/match: "true"
    labels:
        cnpg.io/reload: "true"
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:sQCtZs282jIpco/J/95/gkGiX7w=,iv:qqtfbLeM8mM/MxrqWjtmfIomgy0KFGy+yu6Hq8s5t+A=,tag:216L0/RYFtF8mswmhKIjnQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:r4lxXWZyXhqxwe4Dc6wDWFj35+oFp9BxB6M19qqHLGA7iR/p3ThYvA==,iv:zwSIww6+mPyTzRjUHOKDBH+Xn8tJPk40bph8xXc4WS0=,tag:DmOfkArc4GZ1ihRxv0YVOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VXN5elg2dk1NL3RvZE5u
            cHQ1NmlvQUd3WUt3MTBzTXFFOWQwTk1pcTMwCkVPTTBRUUl5NkpQYkRnMm5PQjcz
            Smh0MWxFWE5oWjMya1ZuRmpIaVdCbjQKLS0tIFBoS29hZi9CcGFBWjV6Mm5yNnhM
            aTl2YjJ1a2RJS3pjYytOeS9OK3hpdjAKsIxOtks15jirpd5FMxNr2IpMkp7/vFYD
            csJySm9u4XJPDyz3qk7zPYYlPalKF2vq4F0dnQZ1zBs1YzUJGElN1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T12:19:49Z"
    mac: ENC[AES256_GCM,data:HmfWxqJUQgWWfsbDa2uyNEcj8glK2s6mE72kapy8Am2wwCIPvO1330EpGA6fIOwdmv3ryTOOliH/qwsGWJJu71i2sKMSuV8UaKYDv8cnSz1CzG/8fLDJE+VRZTyQxiUfHdy2dJY5JZBc7B8Y1GUUaCxnRHxhpa4MqPRPA+YTpwU=,iv:9joBrvngvOgjMsMb4oVLn1b3+Efw1X2OgXB1zlwMVrs=,tag:A1CNBWUZAx5EJIrLy6DknQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
