---
## ref: https://prometheus.io/docs/alerting/alertmanager/
## ref: https://prometheus.io/docs/alerting/latest/configuration/#configuration-file
global:
  resolve_timeout: 5m
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: email
  repeat_interval: 12h
  routes:
    - receiver: heartbeat
      group_interval: 5m
      group_wait: 0s
      matchers:
        - alertname =~ "Watchdog"
      repeat_interval: 5m
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: email
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: heartbeat
    webhook_configs:
      - send_resolved: true
        url: "${UPTIME_HEARTBEAT_URL}"
  - name: "null"
  - name: "email"
    email_configs:
      - to: "${SECRET_DEFAULT_EMAIL}"
        from: "${SECRET_SMTP_ADDRESS}"
        smarthost: "${SECRET_SMTP_SRV}:${SECRET_SMTP_PORT}"
        auth_username: "${SECRET_SMTP_USER}"
        auth_password: "${SECRET_SMTP_PWD}"
        require_tls: true
        # prettier-ignore
        text: >-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }} {{ else if ne .CommonAnnotations.message ""}}{{ .CommonAnnotations.message }} {{ else if ne .CommonAnnotations.description ""}}{{ .CommonAnnotations.description }} {{ else }}{{ .CommonLabels.alertname }}{{ end }}

          {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          {{ if ne .Annotations.summary ""}}*Summary:* {{ .Annotations.summary }} {{ else if ne .Annotations.message ""}}*Message:* {{ .Annotations.message }} {{ else if ne .Annotations.description ""}}*Description:* {{ .Annotations.description }}{{ end }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
