apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name alertmanager-secret
    namespace: observability
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          alertmanager.yaml: "{{ .alertmanager_yaml | b64dec }}"
    dataFrom:
      - extract:
          key: *name
