apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name actions-runner-controller-secret
    namespace: actions-runner-system
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          github_app_id: "{{ .github_app_id }}"
          github_app_installation_id: "{{ .github_app_installation_id }}"
          github_webhook_secret_token: "{{ .github_webhook_secret_token }}"
          github_app_private_key: "{{ .github_app_private_key | b64dec }}"
    dataFrom:
      - extract:
          key: *name
