---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./bjw-s.yaml
  - ./external-secrets.yaml
  - ./forgejo.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stevehipwell.yaml
