apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name authentik-secret
    namespace: security
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          #App
          AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
          AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
          AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
          AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
          AUTHENTIK_REDIS__DB: "{{ .AUTHENTIK_REDIS__DB }}"
          # Email
          AUTHENTIK_EMAIL__HOST: "{{ .email_host }}"
          AUTHENTIK_EMAIL__PORT: "{{ .email_port }}"
          AUTHENTIK_EMAIL__USERNAME: "{{ .email_username }}"
          AUTHENTIK_EMAIL__PASSWORD: "{{ .email_password }}"
          AUTHENTIK_EMAIL__USE_TLS: "{{ .AUTHENTIK_EMAIL__USE_TLS }}"
          AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
          # Postgres
          AUTHENTIK_POSTGRESQL__NAME: "{{ .AUTHENTIK_POSTGRESQL__NAME }}"
          AUTHENTIK_POSTGRESQL__HOST: "{{ .host }}"
          AUTHENTIK_POSTGRESQL__PORT: "{{ .AUTHENTIK_POSTGRESQL__PORT }}"
          AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_POSTGRESQL__USER }}"
          AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
          AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "{{ .AUTHENTIK_POSTGRESQL__USE_PGBOUNCER }}"
    dataFrom:
      - extract:
          key: *name
      - extract:
          key: smtp
      - extract:
          key: postgres-superuser
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name authentik-db-init
    namespace: security
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          INIT_POSTGRES_DBNAME: "{{ .AUTHENTIK_POSTGRESQL__NAME }}"
          INIT_POSTGRES_HOST: "{{ .host }}"
          INIT_POSTGRES_USER: "{{ .AUTHENTIK_POSTGRESQL__USER }}"
          INIT_POSTGRES_PASS: "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
          INIT_POSTGRES_SUPER_PASS: "{{ .password }}"
    dataFrom:
      - extract:
          key: authentik-secret
      - extract:
          key: postgres-superuser
