---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.10.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secret

    authentik:
      # log_level: info
      avatars: "gravatar, initials"
      error_reporting:
        enable: false
        send_pii: false
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      redis:
        host: dragonfly.database.svc.cluster.local
    server:
      # initContainers:
      #   - name: init-db
      #     image: ghcr.io/onedr0p/postgres-init:16.3
      #     imagePullPolicy: IfNotPresent
      #     envFrom:
      #       - secretRef:
      #           name: authentik-db-init
      resources:
        requests:
          cpu: 44m
          memory: 588M
        limits:
          memory: 1002M
      autoscaling:
        enabled: true
        minReplicas: 2
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/icon: authentik.png
          # gethomepage.dev/name: Authentik
          # gethomepage.dev/group: Infrastructure
          # gethomepage.dev/description: OIDC User Management
          # gethomepage.dev/widget.type: authentik
          # gethomepage.dev/widget.url: https://auth.ewatkins.dev
          # gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
          external-dns.alpha.kubernetes.io/target: "external.ewatkins.dev"
        hosts:
          - auth.ewatkins.dev
        https: false
    worker:
      resources:
        requests:
          cpu: 44m
          memory: 443M
        limits:
          memory: 938M
      autoscaling:
        enabled: true
        minReplicas: 2
