apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bkHG,iv:hxQ/kclKAaThKng37BOFry9/G/RxrgFXUH/hVeXGAmA=,tag:n9TK+Y0CbLwANF+eM46QVQ==,type:comment]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:ZuJdm2KAsVv7IqIAqTZ4lqE=,iv:jNC6QgQg9NFerMFBvz28flxBuKSYCqLzz4R0jDVMLkk=,tag:9s7Juv3cB6PPNC0mIuMGTA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:rF32nwRiZLkfp/ZQMMk5C1FIzpOOb//ejYz/ETyO+kE=,iv:oMPZ3xqUbTHpaZiLV22CVZGbHclnM9LcJOqUSabahx8=,tag:ao5IJX9GrNMT/vCSJrYuJw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:HlFbu6/mStyyEaRHiurhDh7IVBk=,iv:DbSf7sdqOqmPo369LHLIiMNOlYkTfOVdoKPYDs9S7Rw=,tag:Ijnm9Riezy+2QhfLirsPug==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:cSgPWFmwIVH2WMTotYZ8yLalSWpk/f6W4kfC3y2JOw5zdVHA2vuv8/UZN7pzry0FaAC+cjmmRAVGCvO5MV+CYjzR9UHMPRqN00VciVU7e8Y=,iv:emPdjC5AAVgYNtQJvGZRHdHrBnjXkEsioztsi3nPcuY=,tag:JLcvuKzDjB37n8CvJ0HuKA==,type:str]
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:IQ==,iv:ZcySD2eMUa6yLXhnsfTT/2Nm7oMWzDkfOcJCTFCgQWg=,tag:gWtsuV21EhethtcIrCO42w==,type:str]
    #ENC[AES256_GCM,data:7xMPj8Cs,iv:p2n2VJvMSw2IgMwtbXF0i+w8MkwkwBhObobIUKEwUeA=,tag:MHBiuxIESm9QcPnOenwRSg==,type:comment]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:ZoJoM5Wltl4JxveEA0g8GA==,iv:zENYyOETln5fU3wL/pkNZVI1esHIy4/CY8GC/kJR7OA=,tag:+eqbp0M+bgUuLUr10F5vig==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:Lez8,iv:LFXk8VbzvQibbDOXDSD9NT7vl6xVVbOh4uYF2dorPVs=,tag:TbAIYJ7hcIrJSURnko22RQ==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:3QOqtHu4pCFd6NpQb79JXrkppXI/BHoR,iv:nQG6KD1dGOXuJFLGep8nb/Pjb62aZ2xxzY9mpu65g0Q=,tag:f21pYM739Y4kaGUMX8qgmg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:AcKPC+K9MWET6JICZ4pjxOdTaQcr71YdZYjm7apIjxWoiQElqs0X6M1q6zMG3nE4Xa0=,iv:sRhQKN+PUFllJZYU3/WZRHR8ErvYbi4rOJjt6myaEN0=,tag:CG4Vt6p60JpalFKcVqIA8Q==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:gNvtJA==,iv:PJ7BMxO1rw8MI91dUN0Jgxeeb8J8ZAsXMP4K26woSKY=,tag:7/nVF30WJ78Zaj00qm4NCA==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:xJeFPbPm87YtT1sIVLXFUMGwy3s25zXQG+YVhzrmVv44Rg==,iv:mF64i9RB9me785l8C7/u94nyWC9bAORQmUav494iExg=,tag:n01jhSEcKaSgVt8HIFj5bA==,type:str]
    #ENC[AES256_GCM,data:pDJIzKUVz+yb,iv:Uygym/3p/OSvVWHnwv8kbmmLbqM14c7by160fnYGN/M=,tag:bJHauo4bMRghggcyXYbO/A==,type:comment]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:E6Wfpne+3Z66,iv:TXuoNgUB3bV+tC7Tm46oQRXqMgoYmFGeu1MI/E3ktuw=,tag:9ojVOsXz2KoyudaVo5L9rQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:myBS6ysHjeDh+ep0f1zwqsGlm5Z08fEPuwgabisKMg2NWL/GGOeeYA==,iv:Ww7DndembbLlx7Y47/trwJTpJLWauaY4UFnImilm25M=,tag:ig6xw0en32QyeYYzDMvCwg==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:TGDnFg==,iv:vfACniZWYBb3tc+I9jf49v1Mkjwn1cMg20zRTj4b1Oc=,tag:h4LBqBnZsERqellxfENClg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:Sj4VKjTNQBwu5g==,iv:ZFFWjiDcRhKkOvtEtD47W2BKuY5JkzmNF7CHR7u4NdE=,tag:iaosOsJWcPWigL8RE8Dpiw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:dc+jzsAZywZE3h1wHQ7AsQ==,iv:bTlFsSUghW3AbfqUVJZ1gMEFa5z/DZSuCfUXP2nZ4oE=,tag:WamU9zup/KuvPLTCizOViA==,type:str]
    AUTHENTIK_POSTGRESQL__USE_PGBOUNCHER: ENC[AES256_GCM,data:6uMWe+M=,iv:kgqW1rpDjndIQRCj2o0sQUgRSQwn9pstyDk0vh4JJQg=,tag:MoVd7b3qOl+rBEqCdEkoCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkRiYnRlcVo5NUpKZGRz
            TTFUWjFYTkNRNGNvZ1JaVUpvdkdQWEpmcDJvCmYrMFUvNExFSXJDSjBzWVc2WFhh
            R3JkSGdzU2J5VjduaURsU0kvMm5XV1EKLS0tIE5XSlNXSUUydjBHOHFrTjJCeXNs
            Q1hUQTk3UTFXblNxSlBLQ2hiNG5keDAKfaAYg8evZJn1bJ87fS/Rc4tuDR+3eZkK
            G4U7x8+noX/OutMegZ0QBYL0X2Lro5F7/W+oxg90nK8B9ueEC3UOvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-03T01:44:57Z"
    mac: ENC[AES256_GCM,data:nKqIlRfwdpvKO6gqZXnLyhh10xUD7qI84fnPIKCLNzz5M5FBhZNwEB2tbrNJFjg2HytWdURqUUJ/qCTCYzFAAOKv1yNRQYgel1WbQmHM78tyNkY2lcRSJ0PfrMfFtXaoUJuzOjmDLmdux88C0Pitx+1Y+snm8pPSwwTlqboNU9k=,iv:CBhNPBJGd9R77D1u2tQVwBxkcmMtbjoR2iwC8ngCol0=,tag:SMo1Kdxwd1616m/Jplwwrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-init
type: Opaque
stringData:
    #ENC[AES256_GCM,data:04Vt2ERNdlHwa9FvNZo=,iv:st/lmLBiV4ZcgrRJ1DoheCyPlt7+oMWkmFgDUfakji4=,tag:zaD7SSRoFAvGDFMCx2ZRYQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:TAjZdsniBMBZ,iv:SYkieQQOgMO/24TWVuYg6kXX42LMmdIy+V+AiaBDiSo=,tag:7Ljw/tRq4+cGlzffvzm2Xg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Dfcqs3COq0/lk4J05fK0Po/W0ZSrVjW0F6Re7Uf+c/qfeDWPwIyuuQ==,iv:YJeGpT3YZmyGlwEbFZ0ybae8lShTF5vWvrlPDvDR2Ck=,tag:v5WbPapah7V5PP3xVyvnfA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:EFE+yFHKfrG20w==,iv:r2rcFblZz4ECgvK+7YeCUpCAdYDHPHAILKB7euf1DRQ=,tag:O1+/ugtZ1XaUULh+TqWpXw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:uHqVY/6UALRl4Xa+PfeHPA==,iv:aO858s/FDOJIgMh/gYbbIRvqa2q3jrYUN/rbNoOJAu0=,tag:/dxeBNxbQb+RnErAaXZKPQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vTmIDh9UFdmczBsNAbPMj7ZXioqhkjaBlsYXVGA3wiaa4bOfpLRb+A==,iv:LiL2INui4/kKGxDo/YPP3LcemXKnN+NX0Q1HtUsOJC8=,tag:Ct9Ue0VvybIbeLK2/VeivA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkRiYnRlcVo5NUpKZGRz
            TTFUWjFYTkNRNGNvZ1JaVUpvdkdQWEpmcDJvCmYrMFUvNExFSXJDSjBzWVc2WFhh
            R3JkSGdzU2J5VjduaURsU0kvMm5XV1EKLS0tIE5XSlNXSUUydjBHOHFrTjJCeXNs
            Q1hUQTk3UTFXblNxSlBLQ2hiNG5keDAKfaAYg8evZJn1bJ87fS/Rc4tuDR+3eZkK
            G4U7x8+noX/OutMegZ0QBYL0X2Lro5F7/W+oxg90nK8B9ueEC3UOvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-03T01:44:57Z"
    mac: ENC[AES256_GCM,data:nKqIlRfwdpvKO6gqZXnLyhh10xUD7qI84fnPIKCLNzz5M5FBhZNwEB2tbrNJFjg2HytWdURqUUJ/qCTCYzFAAOKv1yNRQYgel1WbQmHM78tyNkY2lcRSJ0PfrMfFtXaoUJuzOjmDLmdux88C0Pitx+1Y+snm8pPSwwTlqboNU9k=,iv:CBhNPBJGd9R77D1u2tQVwBxkcmMtbjoR2iwC8ngCol0=,tag:SMo1Kdxwd1616m/Jplwwrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
