apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name gatus-secret
    namespace: observability
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
          PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
          POSTGRES_URI: "{{ .GATUS_URI }}"
          INIT_POSTGRES_DBNAME: "{{ .GATUS_DB }}"
          INIT_POSTGRES_HOST: "{{ .host }}"
          INIT_POSTGRES_USER: "{{ .GATUS_USER }}"
          INIT_POSTGRES_PASS: "{{ .GATUS_PASS }}"
          INIT_POSTGRES_SUPER_PASS: "{{ .password }}"
          SECRET_FLUX_WEBHOOK_URL: "{{ .SECRET_FLUX_WEBHOOK_URL }}"
    dataFrom:
      - extract:
          key: *name
      - extract:
          key: pushover
      - extract:
          key: flux-webhook
      - extract:
          key: postgres-superuser
