---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "ewatkins-dev-staging"
spec:
  secretName: "ewatkins-dev-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "ewatkins.dev"
  dnsNames:
    - "ewatkins.dev"
    - "*.ewatkins.dev"
