apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name minio-loki-secret
    namespace: observability
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          accesskey: "{{ .accesskey }}"
          secretkey: "{{ .secretkey }}"
    dataFrom:
      - extract:
          key: *name
