apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name forgejo-admin-secret
    namespace: development
spec:
    refreshInterval: 10s
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          username: "{{ .username }}"
          password: "{{ .password }}"
          email: "{{ .email }}"
    dataFrom:
      - extract:
          key: *name
