apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: forgejo-admin-secret
spec:
    refreshInterval: 10s
    secretStoreRef:
        name: bitwarden-secrets-manager
        kind: ClusterSecretStore
    data:
        - secretKey: username
          remoteRef:
            key: 47708d05-d962-40d4-b9fc-b20c00440604
        - secretKey: password
          remoteRef:
            key: 1ff8c196-fb18-478e-ba33-b20c0045a661
        - secretKey: email
          remoteRef:
            key: a0988332-0d8c-49e8-823d-b20c0045c77f
