apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    controllers:
      forgejo:
        type: statefulset
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: forgejo-db-init

        containers:
          app:
            image:
              repository: codeberg.org/forgejo/forgejo
              pullPolicy: IfNotPresent
              tag: 7.0.3-rootless@sha256:841b2694942ae0014e17648571a8906c7424021a5fa515b2a90b59aa23056d6f
            env:
              TZ: ${TIMEZONE}
              USER_UID: 1000
              USER_GID: 1000
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2048Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: &port 3000
                  initialDelaySeconds: 200
                  timeoutSeconds: 5
                  periodSeconds: 10
                  successThreshold: 1
                  failureThreshold: 10

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"

    persistence:
      config:
        enabled: true
        existingClaim: forgejo-config-pvc
        globalMounts:
          - path: /etc/gitea
      data:
        enabled: true
        existingClaim: forgejo-data-pvc
        globalMounts:
          - path: /data

    service:
      forgejo-http:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${LB_FORGEJO}
          io.cilium/lb-ipam-sharing-key: "forgejo"
        controller: *app
        ports:
          http:
            port: *port
      forgejo-ssh:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${LB_FORGEJO}
          io.cilium/lb-ipam-sharing-key: "forgejo"
        controller: *app
        ports:
          ssh:
            enabled: true
            port: 2222
            protocol: TCP
            targetPort: 2222

    ingress:
      forgejo:
        className: internal
        hosts:
          - host: git.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: forgejo-http
                  port: *port
