apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: forgejo
      version: 6.0.6
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: openebs-system
  valuesFrom:
    - targetPath: gitea.config.database.USER
      kind: Secret
      name: db-forgejo-admin-secret
      valuesKey: username
    - targetPath: gitea.config.database.PASSWD
      kind: Secret
      name: db-forgejo-admin-secret
      valuesKey: password
  values:
    replicaCount: 1
    strategy:
      type: 'RollingUpdate'
      rollingUpdate:
        maxSurge: '100%'
        maxUnavailable: 0

    image:
      rootless: true

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - SYS_CHROOT
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    postgresql:
      enabled: false
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false

    gitea:
      admin:
        existingSecret: forgejo-admin

      config:
        APP_NAME: 'Forgejo'

        time:
          DEFAULT_UI_LOCATION: ${TIMEZONE}

        repository:
          DEFAULT_BRANCH: main
          DEFAULT_PRIVATE: true

        admin:
          DISABLE_REGULAR_ORG_CREATION: true

        server:
          SSH_PORT: 222

        database:
          DB_TYPE: postgres
          HOST: postgres16-rw.database.svc.cluster.local:5432
          NAME: forgejo
          SCHEMA: public
          SSL_MODE: disable

        cache:
          ADAPTER: redis
          HOST: redis://dragonfly.database.svc.cluster.local:6379/11
        queue:
          TYPE: redis
          CONN_STR: redis://dragonfly.database.svc.cluster.local:6379/10
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://dragonfly.database.svc.cluster.local:6379/12

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    persistence:
      enabled: true
      storageClass: openebs-hostpath

    ingress:
      app:
        className: internal
        hosts:
          - host: git.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
