---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.30.4.0/16"

  LB_POSTGRES: "10.30.4.11"
  LB_FORGEJO: "10.30.4.12"
