apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qIeiSt+h5+JvGEWb,iv:VYa46RK6Bd/rnzHdtZsYQl9RE5zJWPBksoJlmO8Kfac=,tag:8iKU7c2hZoKxzaC1Z9wdRg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:r4e4I3OMocuKIjL9tnN2EyM=,iv:cYtfs1Kq8M3KdRie3s5SfcyqvkKXiZsv8Zr/D8Fwnj4=,tag:Q29eew+0Jbt6mp9hHu/hDQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kyfDFpwdflz7ViLxjRjObTRBIYln75T7mdKhnVI/Ns0iTi0/,iv:7w+GArtB3OBKIaA88NJD5N6VaoW5QHnks5vNIVfgOc4=,tag:DTFMr41AVtRWDzGev++nAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSVdaa29xYXFUbVVldmho
            Y0N2QUR5SEUwS2x0L29EMTJLeFI0OG1sWEdFCjB4enZQbXhGVzhtSEtxbUREQ21t
            dHFNbGRJQUxRU3BtWXFpSWVaMXFSTW8KLS0tIHBNWVZXdjRmWHRnRWdDVW9PVkpB
            cFJESHRxTGN4SXBqa0pZMFM1SGg3NjgKZ7qfck9mxHwH8C6QFI7W8CRutxvJNEt6
            3NDRZoCFE4O1X942vsTxPPowI7naW64RLjbFIoHNb3NUtbAnoT4JFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T04:04:15Z"
    mac: ENC[AES256_GCM,data:q7s/firIwytqXwseeMPDJcg7umTiEUMXJ5Iuf78cae8079Jk0f/lZvUc9ttUcWhJJGFbQU0gcG4uMjtDfKinsOJkASF7ooumgI+8/A7U1XioAQfMesGdWixXxuztYoCbMM6b4tEaLU+gw4IDKQ02cpfNqequX0Xicq8cfQOD+7o=,iv:AoukJy18Av2Vc5cvUAAEe0CJEfGCg5EnrS1pzvrNOaY=,tag:1nUa13ffm0nyj+IFIv4Y6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
