---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &secret sops-age
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden-secrets-manager
  selector:
    secret:
      name: *secret
  template:
    engineVersion: v2
    data:
      &key agekey: |
        {
          "age_agekey": "{{ index . "age.agekey" }}"
        }
  data:
    - match:
        secretKey: *key
        remoteRef:
          remoteKey: *secret
          property: *key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &secret github-deploy-key
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden-secrets-manager
  selector:
    secret:
      name: *secret
  template:
    engineVersion: v2
    data:
      &key deploy-key: |
        {
          "identity": "{{ .identity | b64enc }}",
          "known_hosts": "{{ .known_hosts | b64enc }}"
        }
  data:
    - match:
        secretKey: *key
        remoteRef:
          remoteKey: *secret
          property: *key
