apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name pgadmin-secret
    namespace: database
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
          PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
          config_local.py: "{{ .config_local_py | b64dec }}"
    dataFrom:
      - extract:
          key: *name
