apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Ca5YgsI0o997i/WEitp3VXtC5S8UxBXZDp83JfAYQlQ=,iv:7kmegnu6OActPCTLf77bxU3JU5QrNDYcJTxBYWJnEu8=,tag:NAdQuaJXdbhlDZEvVPFjFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZitwTm15cGJWR1BnUUYv
            cUJadC9pQ3UvTmRjSng4aEZrbmpoRE1zYnh3Cm53cTN6MWk2M1lkb3NMUVRWRTh6
            K3lzeStLNWIyWjhZZ1U5emFCajkxNTAKLS0tIGYrVEoyWkpzZmNqOCswempUVFBU
            RHdBMVVWcDRpTXlwQkgwdmgwU1Nyd2MKtXJo4Jhhk7DxpciLgzvuzl+ydTmV926b
            GffjafS6abOoJywvCZXvXbFvdE/y2WxL/z0EzlbTceEG56mja9QR2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T05:48:41Z"
    mac: ENC[AES256_GCM,data:FIPnz3SNIx0Ms4njRNXgGvyzHtj/b2niahkhBJNTERZXamVUMmKifP06xQ11YROeE+gT5/Cy3BKI6wcodvGDMZIKZzdsnx/sMvB57ff0/TTBnSjFs/IkeH9TsH2V4R7dqpSmf6XPEeCMltd0vs2xyKJEuerIqc4vMLz1QfWtcmI=,iv:5J7XmUGEfKrzJEU0bq23TuaMQzz2IDpH4aiczbWgkrc=,tag:N3c76k9WQDLansrrZJP6Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
