apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name forgejo-db-init
    namespace: development
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          INIT_POSTGRES_DBNAME: "{{ .FORGEJO_DB }}"
          INIT_POSTGRES_HOST: "{{ .host }}"
          INIT_POSTGRES_SUPER_PASS: "{{ .password }}"
          INIT_POSTGRES_USER: "{{ .FORGEJO_USER }}"
          INIT_POSTGRES_PASS: "{{ .FORGEJO_PASS }}"
    dataFrom:
      - extract:
          key: *name
      - extract:
          key: postgres-superuser
