---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master/job.json
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 60
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/ewatkins/postgres-init:16.4
          envFrom:
            - secretRef:
                name: forgejo-db-init
