apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: db-forgejo-admin-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:I1FwZ7YjuljpNLSDcA==,iv:nZ+oH6Zrq66+nEuK0YKRdK4+8E6EQbZG968vu3NVmb8=,tag:0H8jK3H+vviFvedzMimkSA==,type:str]
    password: ENC[AES256_GCM,data:wQHoQAQBnY0RDBVlSlFCAXESkArFnFdge2mNgMfa5olEJXUfwzGTsA==,iv:Qg2nYciPaXW+z3kSTYWnTlUSSAwNYLdYLavq8UL/ul8=,tag:uIvN2N9Ghi7Jj3Fm2aZPQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ve7n3m9ucqtxgfv220gdf7wlgp8vhurx5vspw365g797vwy5pds56p93y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ0g0Y1lDdS9KV1ZDVVBS
            NjlIVS9HdVVSemh4eWlpM1duM3FLZDdtNkhvCjJVUVlmR1d6NVdDU3AvZTRLVVVn
            ZmNRMUcwbkNCV240ZklLckc0Snp1UjAKLS0tIDQvL0JGM01lbkdXMkVVeHFxdi8y
            RWJPNS9sWGEzQWpaRDEzZnRldURMRlEK7fRbZuHbk3vJCx0jgqYMkPTocfzmo5oa
            1BdZ70zhc+QjjjBPGV1VVvds43Z6Iu0IM6SNbKzF+5OEZEO4pnnRUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T16:18:27Z"
    mac: ENC[AES256_GCM,data:z39M34Pn9Ya/TmFCllyWhiEKCYrwUrM+4Jv8LzsVR1Axx48z8rID2MZ5LIG3HsDbhpBIAnUnraLdu021DWT8yOK/AOAYYWFqEwxKniAjEfaxwOAzOJ4QxMlWFV/HCWofoIsHSaAjWWJJ0TziVLgBRMpN0usibhAVbwnr+ORGTJs=,iv:weT61MOtLPyElrhgczkMgCQ9b6NFudElBgfXr/7FeRw=,tag:A/Z3WVPngxtyNfTMaQs4dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
