apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: external-secret-test
    namespace: external-secrets
spec:
    refreshInterval: 10s
    secretStoreRef:
        name: bitwarden-secrets-manager
        kind: ClusterSecretStore
    target:
      name: test-secret
      template:
        engineVersion: v2
        data:
          USERNAME: "{{ .username }}"
          PASSWORD: "{{ .password }}"
          EMAIL: "{{ .email }}"
    dataFrom:
      - extract:
          key: test-secret
